import React from 'react'

const AddItem = () => {
    return (
        <div>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Possimus laboriosam nisi repellat recusandae hic quas mollitia, veniam dolore necessitatibus officia excepturi voluptatum, deleniti a odio aliquid alias at beatae nemo. Voluptatibus nostrum minima eaque, beatae iusto numquam recusandae cupiditate in temporibus! Itaque commodi voluptas corporis exercitationem in, ab veritatis, facilis dolore aliquam maxime consectetur voluptatibus labore quia? Aut, sint delectus! Nam reprehenderit itaque assumenda quisquam cupiditate tenetur praesentium consequuntur veritatis reiciendis a, excepturi amet quam, magni rerum, velit quod natus. Amet obcaecati labore dolore ab repellendus consequatur ipsum, temporibus unde, vel quaerat eum pariatur omnis odio excepturi aliquam laudantium at.
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Possimus laboriosam nisi repellat recusandae hic quas mollitia, veniam dolore necessitatibus officia excepturi voluptatum, deleniti a odio aliquid alias at beatae nemo. Voluptatibus nostrum minima eaque, beatae iusto numquam recusandae cupiditate in temporibus! Itaque commodi voluptas corporis exercitationem in, ab veritatis, facilis dolore aliquam maxime consectetur voluptatibus labore quia? Aut, sint delectus! Nam reprehenderit itaque assumenda quisquam cupiditate tenetur praesentium consequuntur veritatis reiciendis a, excepturi amet quam, magni rerum, velit quod natus. Amet obcaecati labore dolore ab repellendus consequatur ipsum, temporibus unde, vel quaerat eum pariatur omnis odio excepturi aliquam laudantium at.
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Possimus laboriosam nisi repellat recusandae hic quas mollitia, veniam dolore necessitatibus officia excepturi voluptatum, deleniti a odio aliquid alias at beatae nemo. Voluptatibus nostrum minima eaque, beatae iusto numquam recusandae cupiditate in temporibus! Itaque commodi voluptas corporis exercitationem in, ab veritatis, facilis dolore aliquam maxime consectetur voluptatibus labore quia? Aut, sint delectus! Nam reprehenderit itaque assumenda quisquam cupiditate tenetur praesentium consequuntur veritatis reiciendis a, excepturi amet quam, magni rerum, velit quod natus. Amet obcaecati labore dolore ab repellendus consequatur ipsum, temporibus unde, vel quaerat eum pariatur omnis odio excepturi aliquam laudantium at.
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Possimus laboriosam nisi repellat recusandae hic quas mollitia, veniam dolore necessitatibus officia excepturi voluptatum, deleniti a odio aliquid alias at beatae nemo. Voluptatibus nostrum minima eaque, beatae iusto numquam recusandae cupiditate in temporibus! Itaque commodi voluptas corporis exercitationem in, ab veritatis, facilis dolore aliquam maxime consectetur voluptatibus labore quia? Aut, sint delectus! Nam reprehenderit itaque assumenda quisquam cupiditate tenetur praesentium consequuntur veritatis reiciendis a, excepturi amet quam, magni rerum, velit quod natus. Amet obcaecati labore dolore ab repellendus consequatur ipsum, temporibus unde, vel quaerat eum pariatur omnis odio excepturi aliquam laudantium at.
        </div>
    )
}

export default AddItem